# 头部菜单，title: link
menu:
  首页: /
  关于: /infos/about
  归档: /archives

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - https://www.qtings.com/uploads/tracks/1322080660_1481657788_2101911405.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/cover.png

# 默认文章封面图（随机调用,支持外链）
cover: 
  - /img/main/img_0.png
  - /img/main/img_1.png
  - /img/main/img_2.png
  - /img/main/img_3.png
  - /img/main/img_4.png
  - /img/main/img_5.png
  - /img/main/img_6.png
  - /img/main/img_7.png
  - /img/main/img_8.png
  - /img/main/img_9.png
  - /img/main/img_10.png
  - /img/main/img_11.png
  - /img/main/img_12.png
  - /img/main/img_13.png
  - /img/main/img_14.png
  - /img/main/img_15.png
  - /img/main/img_16.png
  - /img/main/img_17.png
  - /img/main/img_18.png
  - /img/main/img_19.png
  - /img/main/img_20.png
  - /img/main/img_21.png
  - /img/main/img_22.png
  - /img/main/img_23.png
  - /img/main/img_24.png
  - /img/main/img_25.png
  - /img/main/img_26.png
  - /img/main/img_27.png
  - /img/main/img_28.png
  - /img/main/img_29.png
  - /img/main/img_30.png
  - /img/main/img_31.png
  - /img/main/img_32.png
  - /img/main/img_33.png
  - /img/main/img_34.png
  - /img/main/img_35.png
  - /img/main/img_36.png
  - /img/main/img_37.png
  - /img/main/img_38.png
  - /img/main/img_39.png
  - /img/main/img_40.png
  - /img/main/img_41.png
  - /img/main/img_42.png
  - /img/main/img_43.png
  - /img/main/img_44.png
  - /img/main/img_45.png
  - /img/main/img_46.png
  - /img/main/img_47.png
  - /img/main/img_48.png
  - /img/main/img_49.png
  - /img/main/img_50.png
  - /img/main/img_51.png
  - /img/main/img_52.png
  - /img/main/img_53.png
  - /img/main/img_54.png
  - /img/main/img_55.png
  - /img/main/img_56.png
  - /img/main/img_57.png
  - /img/main/img_58.png
  - /img/main/img_59.png
  - /img/main/img_60.png
  - /img/main/img_61.png
  - /img/main/img_62.png
  - /img/main/img_63.png
  - /img/main/img_64.png
  - /img/main/img_65.png
  - /img/main/img_66.png
  - /img/main/img_67.png
  - /img/main/img_68.png
  - /img/main/img_69.png
  - /img/main/img_70.png
  - /img/main/img_71.png
  - /img/main/img_72.png
  - /img/main/img_73.png
  - /img/main/img_74.png
  - /img/main/img_75.png
  - /img/main/img_76.png
  - /img/main/img_77.png
  - /img/main/img_78.png
  - /img/main/img_79.png
  - /img/main/img_80.png
  - /img/main/img_81.png
  - /img/main/img_82.png
  - /img/main/img_83.png
  - /img/main/img_84.png
  - /img/main/img_85.png
  - /img/main/img_86.png
  - /img/main/img_87.png
  - /img/main/img_88.png
  - /img/main/img_89.png
  - /img/main/img_90.png
  - /img/main/img_91.png
  - /img/main/img_92.png
  - /img/main/img_93.png
  - /img/main/img_94.png
  - /img/main/img_95.png
  - /img/main/img_96.png
  - /img/main/img_97.png
  - /img/main/img_98.png
  - /img/main/img_99.png
  - /img/main/img_100.png


# 是否显示Twitter分享卡片图像(图像尺寸要求：1200*600，creatorid不需要带@符号。注意：链接必须是完整url，否则Twitter将无法读取图片信息）
twitterpic:
  enable: false
  src: https://bangdream.moe/img/ident.png
  creatorid: yourtwitteridhere

# 是否使用mathjax
mathjax: true

# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: false

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: https://www.facebook.com
    twitter: https://twitter.com
    github: https://github.com/Ledgerbiggg
    wechat: https://img2.imgtp.com/2024/02/11/38gw75oU.png
    email: https://img2.imgtp.com/2024/02/11/wPf9X0wE.png
  
# 备案
beian: 
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '825033'
    # 应用秘钥
    clientSecret: 'aa6da03d6c3ef96e68f31fedbe9396516fdde451'
    # issue仓库名
    repo: 'blog-gitalk-repo'
    # Github名
    owner: 'Ledgerbiggg'
    # Github名
    admin: ['Ledgerbiggg']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Ledger-blog

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/ledger.jpg

# rss文件
rss: atom.xml

# 要使用版权信息可以在这配置并设定许可方式，可以从 https://creativecommons.org/about/cclicenses/ 查询
copyright:
    enable: false
    license: "CC BY-NC-ND"
